### ISSUE TITLE
Best git management method to work on the final script 

### ISSUE THREAD

**Issue by NinjMenon** [jl3392/bme590hrm#10]
We've been reading up on this but we're still not sure what is the best way to approach writing our script. 

Option A : We have one main file "final_program.py" on master and we have a copy of that on our respective branches to work on. When we're done, we each submit pull requests for review and then merge onto master, which effectively keeps master uncluttered and error-free. Git ideally will tell us about conflicts that we can then resolve. 

Option B: We each have a "final_program.py" maintained on our own branches, with no copy on master. When we're done we merge onto master. Not sure how Git will handle this. 

Option A intuitively seems like the right way to do it but too much googling has confused us. Could you guys throw some light on this issue?

**Comment by mlp6** [comment]
I'll propose a third option with this motivation.  Having everyone work on a single file is not ideal b/c of the conflict resolution that you will inevitably have.  Instead, it would be good for each person to work on their own modules that can be imported into a single "main" program.  In as much as those modules and respective tests are independent of each other, all can keep developing and pushing their contributions to master when ready w.o clobbering other folks with changes in the same file.  That would be a much cleaner workflow.
