### ISSUE TITLE
Inquiry about creating multiple classes to distribute the work

### ISSUE THREAD

**Issue by jl3392** [jl3392/bme590hrm#17]
@mlp6 @suyashkumar @ad12 
Hi All,
We're a bit confused on how to begin with implementing the class based approach for our project from a workflow perspective. We're currently looking at grouping some of our existing functions that are similar into separate classes and then merging them somehow into a big class. Is there a better "git" way to approach this problem? We just want to confirm that we are on the right track. 
Thank you very much!

**Comment by mlp6** [comment]
I wouldn't necessarily think immediately about needing to do this in discrete classes (i.e., one class per developer); instead I would encourage your group to decide on a good software design using a class (or classes), and then divide-n-conquer the code implementation.  You can all work on the same class, but version control is no substitute for good group communication on who works on what.  Even if you are working in the same file, you don't want to be concurrently working on the same methods, etc. (that would just be a waste of time, and it will create lots of conflicts).

**Comment by jl3392** [comment]
Thanks! We decided to create one main script and work on different functions.
