### ISSUE TITLE
Will age factor be considered for the Tachy-/bradycardia

### ISSUE THREAD

**Issue by jl3392** [jl3392/bme590hrm#4]
The upper threshold of human's heart beat is based on age. For detecting Tachy-/bradycardia in the ECG trace, will the input ECG files give any information about patients' age? Or do we need to set a certain percentage to predict the disease situations. 
For instance, if an instantaneous HR is 20% higher than the average HR, it will be considered as Tachycardia.

**Comment by suyashkumar** [comment]
Hey @jl3392 great question! The ECG files will not contain any information about the patient's age, however you have great intuition here thinking about what the right threshold should be and that it might change.

Given that it might vary by patient age, BMI, resting heart rate etc. you may want to ensure that these lower and upper thresholds are easily configurable in your code that have a good "normal case" default value that you may determine. 

You may also choose to create optional functionality to allow for the input of age or other patient features that may aid in computing these thresholds if you're interested. Whatever features you add though, do make sure that your code still runs on the input CSV without _needing_ to specify any additional patient factors. (Specification of such factors should be optional).

**Comment by jl3392** [comment]
Thank you @suyashkumar
