### ISSUE TITLE
Instant Heart Rate - update every 'x' secs or continuously? 

### ISSUE THREAD

**Issue by NinjMenon** [jl3392/bme590hrm#6]
edited this question because I felt the original question wasn't super clear : For the instantaneous HR, how often would we ideally update it or rather, how many cardiac beats would we consider in this calculation? 
I know that Fitbits and the sort use about 2-3 seconds to update their instantaneous HR. Should we be looking to do the same?

**Comment by ad12** [comment]
There's many different ways to approach this problem. The prompt leaves it open ended on purpose so you can determine what might be the best way/ways to do so. There's no right answer, but there are some ways that are better for certain scenarios versus others.
